name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: build_type
    attributes:
      label: What Monal Release channel are you using? If you did install Monal via the Apple AppStore, please select AppStore.
      multiple: false
      options:
        - AppStore
        - Beta
        - Alpha
    validations:
      required: true
  - type: input
    id: ios_version
    attributes:
      label: iOS system version
      description: What iOS version are you using? Open Settings, scroll down until "General", select "Info" and report "Software version".
      placeholder: "14.7"
    validations:
      required: false
  - type: input
    id: ios_monal__version
    attributes:
      label: iOS Monal version
      description: What Monal version are you using? Open Monal, select top left icon, scoll down until "Version".
      placeholder: "5.0.1"
    validations:
      required: false
  - type: input
    id: mac_version
    attributes:
      label: macOS system version
      description: What macOS version are you using?
      placeholder: "14.7"
    validations:
      required: false
  - type: input
    id: mac_monal__version
    attributes:
      label: macOS Monal version
      description: What Monal version are you using?
      placeholder: "5.0.1"
    validations:
      required: false
  - type: input
    id: xmpp_server
    attributes:
      label: Used XMPP server (domain)
      description: Which XMPP server are you using? Open Monal, select top left icon, see the very top information an report the domain after the @ symbol.
      placeholder: chat.example.org
    validations:
      required: true
  - type: dropdown
    id: xmpp_server_software
    attributes:
      label: Which XMPP-Server software are you using? Try to reach out to your provider if possible.
      multiple: false
      options:
        - Prosody
        - ejabberd
        - jackal
        - openfire
        - other
    validations:
      required: false
  - type: input
    id: xmpp_server_software_version
    attributes:
      label: XMPP Server Software
      description: Which software version is the XMPP-Server running? Try to reach out to your provider if possible.
      placeholder: "1.0.1"
    validations:
      required: false
  - type: dropdown
    id: account_cnt
    attributes:
      label: How many accounts are you using in Monal?
      multiple: false
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - ">= 6"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A problem happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If you can reproduce your issue: send us your log file (`Settings/Debug`) to info (at) monal (dot) im.
        PLEASE BE AWARE THAT THIS CAN PROVIDE SENSITIVE INFORMATION TO THE DEVELOPERS (which of course will not abuse this, but you are informed now!)
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: cross-check-checkbox
    attributes:
      label: Related Issues
      options:
        - label: I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels
          required: true
  - type: checkboxes
    id: xep-checkbox
    attributes:
      label: XEP-Check
      options:
        - label: I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings
          required: true
  - type: checkboxes
    id: notifications-checkbox
    attributes:
      label: Notifications-Menu
      options:
        - label: I have checked that all checkboxes are ticked under Settings --> Notifications
          required: true
